services:
  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "5000:5000"
      
  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
