services:
  backend:
    build: ./backend
    container_name: backend_app_2
    restart: always
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: frontend_app_2
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend
